### PR TITLE
Add a deauthenticate function 

### PR DESCRIPTION
**Pull request by nstCactus**
I needed a way to go back to an un-authenticated state after initializing the directus SDK with the token:

````js
const directusSdk = new DirectusSdk.RemoteInstance(
  accessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  url:         'http://directus.example.com',
});
````

I first tried to simply clear the `accessToken` property (`directusSdk.accessToken = null`) but even after I did, subsequent request to the directus API still included the `Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxx` HTTP header. Digging a little deeper, I found out that you also need to clear the `_requestHeaders.Authorization` property.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @nstCactus! Thanks for the added method 🙂 

I thought the _requestHeaders would re-create the headers object each call, seeing it's a getter.. 🤔 

https://github.com/nstCactus/directus-sdk-javascript/blob/4407dac0c85d70d64d83409a16c61d6b6575d285/remote.js#L25-L33

Ohhh I see what happens. It (correctly) only appends the accessToken when it exists, but it uses the stored `this.headers` as starting point. So if you had an accessToken before, it still exists in `this.headers`.

Instead of `delete`ing this._requestHeaders, lets add an `else` statement to that `this._requestHeaders` getter so it removes the `Authorization` header when it's in `this.headers` but `this.accessToken == null` 👍

**Comment by nstCactus** [comment]
IMHO, the issue is this instruction at [line 26][line-26] (`const headers = this.headers || {};`) which causes both `headers` and `this.headers` to reference the same object. When you mutate either one, the changes are reflected in the other.

I think the original intention was to make `headers` a copy of `this.headers`. 

An easy way to achieve this is to replace [line 26][line-26] with:
```js
const headers = Object.assign({}, this.headers);
```

[line-26]: https://github.com/nstCactus/directus-sdk-javascript/blob/4407dac0c85d70d64d83409a16c61d6b6575d285/remote.js#L26

**Comment by rijkvanzanten** [comment]
Does that solve the issue you were trying to solve in this PR too?

**Comment by nstCactus** [comment]
Yes it does. But you may need to adjust your babel configuration. With you current babel config, `Object.assign()` isn't transpiled, which is fine as long as you don't want to support Internet Explorer:

Here is the compatibility table: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

**Comment by nstCactus** [comment]
Just pushed the fix. If you need some adjustments (squashing the commits into a single one, removing the `deauthenticate()` method…), just let me now.

**Comment by rijkvanzanten** [comment]
The `deauthenticate` does nothing more than setting accessToken to null, but I do believe it helps in the developers perspective. People will be looking for a logout / de-auth, so lets leave it in 🙂

**Comment by rijkvanzanten** [comment]
I squash merge most pull requests so no need to cleanup the commits 😉

**Comment by rijkvanzanten** [comment]
This has been released on [NPM](https://www.npmjs.com/package/directus-sdk-javascript) in version 2.12.0.

Thanks for the help @nstCactus! 😄

**Pull request merged**
