### PR TITLE
Add ability to configure how access token is sent and additional URL params to POST, DELETE and PUT item requests

### PR DESCRIPTION
**Pull request by simonasdev**
Added a new constructor option: `accessTokenType`. It is by default `header`, which is current behaviour. One can set it to `parameter` and then access token will be sent as query parameter and not as `Authorization` header.

Also `createItem`, `deleteItem` and `updateItem` functions now accept params object as the last parameter, which will be forwarded to axios URL parameters.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks!

I'll still merge it in, but why do we need this? What are the usecases? 🙂

**Comment by rijkvanzanten** [comment]
Also, lets make sure this plays nicely with the other PR I forgot to merge in until now 😬

**Comment by simonasdev** [comment]
The use case for different access token sending is because header authorization wasn't working in my backend for some reason :D but appending URL parameters to POST, PUT and DELETE requests allows clients to control what gets returned in the response object, for example adding `columns=id` parameter allows us to get only the id of the object that was created/updated.
These changes were implemented because of issues in a personal project, but since the backend API supports it, I thought that client SDK should too, so here we are now.

I'll fix merge conflicts later this week probably

**Comment by simonasdev** [comment]
@rijkvanzanten review when you can

**Pull request merged**
