### PR TITLE
Use correct dist/remote.js file as main

### PR DESCRIPTION
**Pull request by frbl**
fixes https://github.com/directus/directus-sdk-javascript/issues/32?

### CODE REVIEW

**Comment by frbl** [comment]
Please check this carefully though, I'm not an expert on neither directus nor js...

**Comment by weeksseth** [comment]
Using dist/remote.js as main does not work. It appears that using index.js as main works for me. I was able to successfully build and deploy a react app with a fork using index.js as main.

**Comment by rijkvanzanten** [comment]
Thanks for the heads up @weeksseth!

I didn't realize the `main` file was still pointing to `dist/index.js` (a file that doesn't even exist 😧)

I'll update the package.json so it points to the `index.js` file.

I haven't had any troubles using `index.js` or `remote.js` in projects myself, so I consider that to be a "fix" for now..

**Comment by rijkvanzanten** [comment]
I'm working on the next major version of the SDK as we speak, so I'll try to make sure the whole build setup is done right this time

**Comment by frbl** [comment]
You're right, it did not work for me either (finally had the option to test it out). I do run in the problem that my webpack fails on this plugin because of this build / non-compiled piece of code;

``` javascript
ERROR in 0.fddd02a44995a2c4d971.chunk.js from UglifyJs
Unexpected token: name (RemoteInstance) [0.fddd02a44995a2c4d971.chunk.js:2223,6]

ERROR in 1.e9b0735606ce481a3f61.chunk.js from UglifyJs
Unexpected token: name (RemoteInstance) [1.e9b0735606ce481a3f61.chunk.js:2297,6]

ERROR in 2.5740ac466f3ef7806fa4.chunk.js from UglifyJs
Unexpected token: name (RemoteInstance) [2.5740ac466f3ef7806fa4.chunk.js:2136,6]
```
What did work in my case though was changing the index file to 

```
module.exports = {
  RemoteInstance: require('./dist/remote')
};
```
and updating the `package.json` to set `index.js` as its main file. Its a bit of a weird solution though. What might work (but again, I'm not a webpack pro) is to set *.js as entry point for the compilation, and then point the `package.json` to the `/dist/remote.js` file (which then includes the `index.js` file). 

Would you like me to try and make a pr for this?

**Pull request closed without merging**
