### PR TITLE
Added updateTable method

### PR DESCRIPTION
**Pull request by FreeleX**
This is useful for example for creating table intended to contain only a single item/record

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @FreeleX!

Sending a `PUT` request to `/api/1.1/tables` is not a valid action in the Directus API, so this won't work I'm afraid..

You can create tables by sending a `POST` to `/api/1.1/tables` and update the Directus table-meta information by updating the `directus_tables` information (`PUT /api/1.1/directus_tables`)

**Comment by FreeleX** [comment]
Hi @rijkvanzanten,

Thank you for your review.

However while trying, to PUT /api/1.1/directus_tables or GET /api/1.1/directus_tables I receive
<h2>Sorry, this page isn't available.</h2>
and PUT /api/1.1/tables/directus_tables always returns success but does not modify anything (could you please provide me with data for PUT or link to related piece of documentation?)

And I've found this piece of code (it seems like because of it my proposed code works) https://github.com/directus/directus/blob/master/api/routes/A1/Table.php#L263

**Comment by rijkvanzanten** [comment]
Oh I'm sorry, gave you the wrong endpoint... Should've been `PUT /api/1.1/tables/directus_tables/[row-id]`: https://api.getdirectus.com/1.1/#Update_Item.

**Comment by FreeleX** [comment]
Thank you, it worked. Would it be appropriate to introduce new updateTable method doing this.updateItem('directus_tables', tableId, data) or should it be renamed to smth like updateTableViaSystemTables ? Or is it not worth adding such logic as public method?

**Comment by rijkvanzanten** [comment]
Good question @FreeleX. I like the idea of introducing it as a "convenience method", but on the other hand, we tried to match the available methods 1-to-1 to the API to prevent having to write separate documentations for all the different SDKs..

**Comment by rijkvanzanten** [comment]
I'll close this PR as the original code implementation is invalid. We'd love to discuss adding this convenience table update endpoint to the API over on [our Slack channel](https://slack.getdirectus.com).

**Pull request closed without merging**
