### PR TITLE
Added rollup to transpile code ES6->ES5

### PR DESCRIPTION
**Pull request by milasevicius**
Using create-react-app I was getting an error `Failed to minify the code from this file: ./node_modules/directus-sdk-javascript/remote.js:4`, because file was not transpiled.

Usage: Run `npm run build` before publishing package, you will get production ready js file, which will be transpiled and ready for all major browsers.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Awesome addition! Thanks 😄 

I was just wondering though, since this also bundles the file into a single `.js` file, won't that de-optimize bundling and minification if you already have the dependencies in your project (f.e. won't you end up with two copies of `axios` in your bundle if you also use `axios` separately in your project)?

**Comment by milasevicius** [comment]
You are right. I've updated rollup config, which excludes `axios` and `qs` from bundle.

**Comment by rijkvanzanten** [comment]
Thanks for the update!

I was wondering about another thing though.. This bundles everything in a single `index.js` file, which breaks the recommended `require('directus-sdk-javascript/remote')` way of importing. The reason we kept in this split in the first place is that there is eventually going to be a `local` version which can directly access the database and we don't want to force people to include the whole SDK library if they're only going to use half of it..

Maybe we shouldn't bundle the files and just transpile them? Have the output be something like:
```
dist
├── index.js
├── remote.js
└── local.js
```

What are your thoughts on this?

**Comment by milasevicius** [comment]
To be honest, I am not sure what is the best way to do this.

One thing I have in mind is: in index.js we could write something like `export { local, remote }` and then users can import it using `import { remote } from 'directus-sdk-javascript`.

Other way is to define multiple entry / destination points in rollup (if that is possible).

**Comment by rijkvanzanten** [comment]
That's pretty much what's there in `index.js` right now, except it's in CommonJS. 

Right now, importing the `RemoteInstance` like this `const {RemoteInstance} = require('directus-sdk-javascript');` works like expected, but if you would bundle that in production, it would pull in both the local and remote instances, as they're both required in the main `index.js` file....

It might be a nice to have to have a bundled/minified version of the `RemoteInstance` after all for browser use through CDN services like https://unpkg.com/ 😄 

I feel like we're going down the rabbit hole here haha


Sooo concluding, what we ideally want is:

```
src
├── index.js         // For convenience import, not recommended
├── remote.js
└── local.js

dist
├── index.js         // For convenience import, not recommended
├── remote.js        // Just transpiled, not bundled
├── remote.min.js    // Bundled / minified / transpiled for direct browser use
└── local.js         // Just transpiled, not bundled
```

**Comment by milasevicius** [comment]
This seems logical, but unfortunately I cannot update my PR with above functionality in the near future. Maybe after month or so.

If you are willing to do this, then you need to update rollup configuration file.

**Comment by rijkvanzanten** [comment]
Hey @milasevicius!

I have some time to pick this up today.

I'll update your config to bundle everything from the `remote.js` file into a browser-ready bundle (including dependencies).

The recommended way of using the SDK would still be importing the non-bundled version and bundle it yourself into your application, to prevent duplicates.

Your addition would make it possible to include the SDK via `unpkg` or direct downloads

**Comment by milasevicius** [comment]
Sounds good!

**Pull request merged**
